# tent_tests.py — extracted from tent_v4_parallel_tracks.py
# Canonical test suite for TENT engine

ARC_TESTS = [
    ("The input grid is turned clockwise by 90 degrees to produce the output", "rotate_90"),
    ("Rotate the entire pattern 90 degrees clockwise", "rotate_90"),
    ("The transformation applies a quarter turn rotation clockwise", "rotate_90"),
    ("Each cell position rotates 90 degrees around the center", "rotate_90"),
    ("The grid undergoes clockwise rotation by ninety degrees", "rotate_90"),
    ("Apply a 90 degree clockwise rotation to the grid orientation", "rotate_90"),
    ("The output is the input rotated one quarter turn clockwise", "rotate_90"),
    ("Spinning the grid 90 degrees clockwise produces the result", "rotate_90"),
    ("The pattern is flipped horizontally creating a mirror image left to right", "mirror_h"),
    ("Reflect the grid along the vertical axis creating horizontal symmetry", "mirror_h"),
    ("Mirror the pattern horizontally so left becomes right", "mirror_h"),
    ("The transformation reflects the grid horizontally", "mirror_h"),
    ("Apply horizontal reflection to create a mirror image", "mirror_h"),
    ("Flip the entire grid left to right creating a horizontal mirror", "mirror_h"),
    ("The output is a horizontal reflection of the input pattern", "mirror_h"),
    ("The grid is reflected vertically flipping top to bottom", "mirror_v"),
    ("Mirror the pattern vertically so top becomes bottom", "mirror_v"),
    ("Flip the grid upside down creating a vertical mirror reflection", "mirror_v"),
    ("Apply vertical reflection so the top row becomes the bottom row", "mirror_v"),
    ("The output is the input inverted vertically top to bottom", "mirror_v"),
    ("Reflect the entire grid along the horizontal axis vertically", "mirror_v"),
    ("The enclosed region is filled with a solid color flooding the area", "fill_color"),
    ("Fill the interior enclosed region with a solid uniform color", "fill_color"),
    ("Apply flood fill to paint the enclosed area solid", "fill_color"),
    ("The transformation fills every cell inside the enclosed boundary", "fill_color"),
    ("Color the entire interior region enclosed by the border", "fill_color"),
    ("Flood fill the area inside the shape with a single solid color", "fill_color"),
    ("The small pattern is repeated to tile and fill the entire larger grid", "pattern_repeat"),
    ("Tile the output grid by repeating the input pattern motif", "pattern_repeat"),
    ("The motif is tessellated to fill the entire output space", "pattern_repeat"),
    ("Replicate the pattern across the grid creating a tiling", "pattern_repeat"),
    ("The input pattern is duplicated and extended to tile the output", "pattern_repeat"),
    ("Copy the motif repeatedly to tessellate and fill the grid", "pattern_repeat"),
    ("A tiling operation replicates the motif extending it to fill space", "pattern_repeat"),
    ("Only the border outline edge of the shape remains in the output", "border_extract"),
    ("Extract the boundary contour perimeter of each shape", "border_extract"),
    ("The shape boundary perimeter frame is extracted as the output", "border_extract"),
    ("Remove the interior leaving only the outer border outline", "border_extract"),
    ("The transformation extracts only the edge contour of objects", "border_extract"),
    ("Keep the perimeter boundary frame and remove interior cells", "border_extract"),
    ("The pattern is enlarged scaled up to double its original size", "scale_up"),
    ("Magnify the grid by a scale factor enlarging each cell", "scale_up"),
    ("Upscale the pattern to a bigger size by zooming in", "scale_up"),
    ("Expand the grid making the pattern bigger through scaling", "scale_up"),
    ("Double the size of each element enlarging the whole pattern", "scale_up"),
    ("The transformation magnifies and enlarges the input pattern", "scale_up"),
    ("The grid is shrunk reduced compressed to a smaller size", "scale_down"),
    ("Minimize the pattern by downscaling and reducing resolution", "scale_down"),
    ("Shrink the grid condensing it into a smaller version", "scale_down"),
    ("Reduce the size of the pattern by compressing and shrinking", "scale_down"),
    ("Downscale the input to a miniaturized smaller output", "scale_down"),
    ("The transformation condenses and shrinks the pattern smaller", "scale_down"),
    ("Colors are swapped red becomes blue and blue becomes red throughout the grid", "color_swap"),
    ("The transformation remaps each color to a different substitute color", "color_swap"),
    ("Apply a color permutation swapping and remapping every color", "color_swap"),
    ("Replace all instances of one color with another color remap", "color_swap"),
    ("Recolor the grid by substituting each color with its mapped replacement", "color_swap"),
    ("The color mapping transforms red to blue and blue to red throughout", "color_swap"),
    ("Swap substitute and remap the colors according to the transformation rule", "color_swap"),
    ("Each shape falls to the bottom of the grid like gravity pulls them down", "gravity_fall"),
    ("Apply gravity so all colored pixels drop and settle at the bottom", "gravity_fall"),
    ("Pixels descend under gravity and stack at the bottom of the grid", "gravity_fall"),
    ("All objects sink to the bottom as if weight and gravity pull them", "gravity_fall"),
    ("The transformation makes everything fall and collapse downward", "gravity_fall"),
    ("Under gravitational descent all shapes drop to the bottom and stack", "gravity_fall"),
    ("Objects settle at the bottom as gravity pulls them to descend and sink", "gravity_fall"),
    ("Count the number of distinct separate objects shapes in the grid", "count_objects"),
    ("Enumerate and tally the total quantity of separate shapes", "count_objects"),
    ("The output is the census count of distinct objects in the input", "count_objects"),
    ("Tally the number of separate disconnected shapes and objects", "count_objects"),
    ("Count and enumerate every distinct object shape in the grid", "count_objects"),
    ("The total quantity of separate objects is counted and tallied", "count_objects"),
    ("Objects are sorted arranged in order from largest to smallest by size", "sort_size"),
    ("Rank and arrange the shapes in a hierarchy by their size", "sort_size"),
    ("Sort the objects into sequence ordered by size from largest to smallest", "sort_size"),
    ("The shapes are arranged in rank order according to their size", "sort_size"),
    ("Order the objects by size creating a sorted arrangement hierarchy", "sort_size"),
    ("The output shows only where both grids overlap their intersection", "boolean_and"),
    ("Boolean intersection shows cells that are common to both inputs", "boolean_and"),
    ("Only pixels present in both grids appear showing the shared overlap", "boolean_and"),
    ("Apply a boolean mask keeping only the intersecting common cells", "boolean_and"),
    ("The intersection of the two grids shows only overlapping shared pixels", "boolean_and"),
    ("The two grids are combined merged together showing the union", "boolean_or"),
    ("Overlay and superimpose both grids combining them into a union", "boolean_or"),
    ("Merge the two inputs together showing either grid combined", "boolean_or"),
    ("The boolean union combines and overlays both grids together", "boolean_or"),
    ("Superimpose and merge both grids into a single combined overlay", "boolean_or"),
    ("The half pattern is completed using symmetry to make the whole shape", "symmetry_complete"),
    ("Reconstruct the missing half using symmetric reflection to complete it", "symmetry_complete"),
    ("Complete the pattern by mirroring the existing half symmetrically", "symmetry_complete"),
    ("The partial symmetric shape is finished by reconstructing the missing half", "symmetry_complete"),
    ("Use symmetry to complete and finish the half pattern making it whole", "symmetry_complete"),
    ("Reconstruct the whole symmetric pattern from the given half", "symmetry_complete"),
    ("The pattern is shifted translated by an offset to a new position", "translate"),
    ("Slide and displace the entire pattern by a fixed offset", "translate"),
    ("Move the objects to a new position via translation displacement", "translate"),
    ("The grid content is repositioned by sliding it with an offset", "translate"),
    ("Translate and shift the pattern to a displaced new position", "translate"),
    ("Extract a subgrid window from the larger input grid", "crop"),
    ("Crop and isolate a specific region from the full grid", "crop"),
    ("The output is a cutout subregion extracted from the input", "crop"),
    ("Select and extract a rectangular window from the grid", "crop"),
    ("Isolate and crop a specific subgrid region from the input", "crop"),
    ("Remove spurious noise artifacts leaving the clean pattern", "denoise"),
    ("Filter and purify the grid by removing noise and artifacts", "denoise"),
    ("Clean the grid by denoising and removing spurious pixels", "denoise"),
    ("The transformation smooths and purifies by removing noise artifacts", "denoise"),
    ("Denoise the input by filtering out spurious artifact pixels", "denoise"),
    ("xyzzy plugh nothing relevant here at all gibberish", None),
    ("the quick brown fox jumps over the lazy dog", None),
    ("I would like to order a large pepperoni pizza please", None),
    ("What time does the bus arrive at the station tomorrow morning", None),
    ("My favorite movie is about a wizard who rides a bicycle", None),
    ("The weather forecast calls for partly cloudy skies tonight", None),
    ("Please remind me to buy groceries on Tuesday afternoon", None),
    ("Tell me a joke about a chicken crossing a road", None),
    ("How do I reset my password for my email account", None),
    ("The restaurant on fifth street serves excellent seafood", None),
    ("I need directions to the nearest gas station please", None),
    ("What is the capital of a country that doesn't exist", None),
    ("My cat likes to sleep on top of the refrigerator", None),
    ("The concert tickets went on sale yesterday morning", None),
    ("How do you properly fold a fitted bed sheet neatly", None),
    ("The train from Boston to New York takes four hours", None),
    ("I forgot my umbrella at the coffee shop this morning", None),
    ("The meeting has been rescheduled to next Wednesday", None),
    ("Which brand of laundry detergent works best on stains", None),
    ("The library closes at nine pm on weeknights usually", None),
]

GPQA_TESTS = [
    ("What principle states that position and momentum cannot be simultaneously known with arbitrary precision", "heisenberg"),
    ("The uncertainty relation between conjugate observables limits simultaneous measurement", "heisenberg"),
    ("Heisenberg showed that measuring position precisely makes momentum uncertain", "heisenberg"),
    ("What equation describes the time evolution of a quantum mechanical wavefunction", "schrodinger"),
    ("The Hamiltonian operator governs the wavefunction evolution in the Schrodinger equation", "schrodinger"),
    ("The eigenstate equation for quantum systems involves the Hamiltonian and psi", "schrodinger"),
    ("When light above threshold frequency hits a metal surface and ejects electrons", "photoelectric"),
    ("Einstein explained the photoelectric effect using photon energy and work function", "photoelectric"),
    ("Electrons are ejected from metal when photon frequency exceeds the threshold", "photoelectric"),
    ("What distribution describes velocity of particles in an ideal gas at thermal equilibrium", "maxwell_boltzmann"),
    ("The statistical distribution of molecular speeds in a gas depends on temperature", "maxwell_boltzmann"),
    ("Maxwell and Boltzmann derived the kinetic velocity distribution for gas molecules", "maxwell_boltzmann"),
    ("Time dilation and length contraction occur at speeds approaching the speed of light", "special_relativity"),
    ("The Lorentz transformation describes how spacetime coordinates change between frames", "special_relativity"),
    ("Special relativity predicts that moving clocks run slower due to time dilation", "special_relativity"),
    ("No two identical fermions can occupy the same quantum state simultaneously", "pauli_exclusion"),
    ("The Pauli exclusion principle explains electron configuration and the periodic table", "pauli_exclusion"),
    ("Antisymmetric wavefunctions for identical fermions enforce the exclusion principle", "pauli_exclusion"),
    ("Planck derived the blackbody radiation spectrum resolving the ultraviolet catastrophe", "black_body"),
    ("Thermal radiation from a blackbody follows the Planck distribution with temperature", "black_body"),
    ("The Stefan Boltzmann law gives total blackbody emissive power proportional to T fourth", "black_body"),
    ("A moving source causes the observed frequency to shift higher or lower", "doppler"),
    ("Redshift and blueshift of waves depend on relative motion of source and observer", "doppler"),
    ("The Doppler effect changes the frequency of waves from moving sources", "doppler"),
    ("When light passes between media it bends according to the indices of refraction", "snell"),
    ("Snell law of refraction relates the angle of incidence to the transmitted angle", "snell"),
    ("The force between two charges follows an inverse square law with distance", "coulomb"),
    ("Coulomb law describes the electrostatic force between charged particles", "coulomb"),
    ("A changing magnetic flux through a coil induces an electromotive force", "faraday"),
    ("Faraday law of electromagnetic induction relates EMF to rate of flux change", "faraday"),
    ("What equation models enzyme kinetics relating reaction rate to substrate concentration", "michaelis_menten"),
    ("Michaelis Menten kinetics describes how enzyme velocity depends on substrate with Vmax and Km", "michaelis_menten"),
    ("The enzyme substrate complex reaches saturation described by Michaelis Menten", "michaelis_menten"),
    ("Allele frequencies remain constant in a population without evolutionary forces", "hardy_weinberg"),
    ("Hardy Weinberg equilibrium predicts genotype frequencies from allele frequencies", "hardy_weinberg"),
    ("Population genetics equilibrium requires no mutation selection drift or migration", "hardy_weinberg"),
    ("The citric acid cycle in mitochondria oxidizes acetyl CoA to produce NADH", "krebs_cycle"),
    ("The TCA Krebs cycle is the central hub of cellular oxidative respiration", "krebs_cycle"),
    ("Acetyl CoA enters the citric acid cycle producing ATP NADH and FADH2", "krebs_cycle"),
    ("Genetic information flows from DNA to RNA to protein in the central dogma", "central_dogma"),
    ("Transcription converts DNA to RNA then translation produces protein", "central_dogma"),
    ("The central dogma describes replication transcription and translation of genetic code", "central_dogma"),
    ("Mendel discovered that traits segregate independently during inheritance", "mendel"),
    ("Dominant and recessive alleles determine phenotype according to Mendel laws", "mendel"),
    ("Punnett squares predict offspring genotype ratios from Mendelian inheritance", "mendel"),
    ("The urea cycle converts toxic ammonia to urea for excretion in the liver", "krebs_urea"),
    ("Ornithine citrulline and arginine are intermediates in the urea nitrogen cycle", "krebs_urea"),
    ("Ammonia detoxification occurs through the urea cycle in hepatocytes", "krebs_urea"),
    ("The second law of thermodynamics states entropy of an isolated system never decreases", "entropy_thermo"),
    ("Boltzmann entropy counts the number of microstates consistent with a macrostate", "entropy_thermo"),
    ("A system at chemical equilibrium shifts to counteract an applied stress", "le_chatelier"),
    ("Le Chatelier principle predicts how equilibrium responds to concentration changes", "le_chatelier"),
    ("Increasing pressure shifts equilibrium toward the side with fewer gas moles", "le_chatelier"),
    ("Gibbs free energy determines whether a reaction is thermodynamically spontaneous", "gibbs_free"),
    ("Delta G equals delta H minus T delta S determines spontaneity", "gibbs_free"),
    ("A negative Gibbs free energy change indicates a spontaneous thermodynamic process", "gibbs_free"),
    ("Carbon forms sp3 tetrahedral sp2 trigonal planar or sp linear molecular geometry", "orbital_hybridization"),
    ("Orbital hybridization explains molecular bonding geometry and bond angles", "orbital_hybridization"),
    ("The mixing of atomic orbitals creates hybrid sp3 sp2 sp bonding geometries", "orbital_hybridization"),
    ("The Nernst equation relates electrode potential to concentration in electrochemistry", "nernst"),
    ("Electrochemical cell voltage depends on concentration through the Nernst equation", "nernst"),
    ("The reduction potential of a galvanic cell varies with reactant concentration", "nernst"),
    ("Henderson Hasselbalch equation relates buffer pH to pKa and acid base ratio", "henderson_hasselbalch"),
    ("Buffer pH equals pKa plus log of conjugate base over acid concentration", "henderson_hasselbalch"),
    ("The dissociation equilibrium of a buffer is described by Henderson Hasselbalch", "henderson_hasselbalch"),
    ("The Arrhenius equation relates reaction rate constant to temperature and activation energy", "arrhenius"),
    ("Rate constant increases exponentially with temperature according to Arrhenius", "arrhenius"),
    ("Activation energy determines how reaction rate depends on temperature exponentially", "arrhenius"),
    ("PV equals nRT is the ideal gas law relating pressure volume temperature and moles", "ideal_gas"),
    ("Boyle Charles and Avogadro laws combine into the ideal gas equation PV nRT", "ideal_gas"),
    ("What is the best recipe for chocolate chip cookies with walnuts", None),
    ("How do I train my golden retriever puppy to sit and stay", None),
    ("What are the lyrics to the national anthem of a made up country", None),
    ("Tell me about the history of roller skating in rural Montana", None),
    ("How do I fix a leaky faucet in my bathroom sink", None),
    ("What is the population of unicorns in the forest of dreams", None),
    ("Describe the migration patterns of imaginary purple butterflies", None),
    ("How many calories are in a slice of pepperoni pizza", None),
    ("What is the airspeed velocity of an unladen swallow", None),
    ("How do I change the wallpaper on my phone settings", None),
    ("The basketball game last night was really exciting to watch", None),
    ("My neighbor plays loud music every Saturday afternoon", None),
    ("How do I plant tomatoes in a raised garden bed properly", None),
    ("What year was the bicycle invented and who made it first", None),
    ("The traffic on the highway was terrible this morning commute", None),
    ("How do you properly iron a dress shirt without wrinkles", None),
    ("What is the thread count of good quality bed sheets", None),
    ("My car needs an oil change every five thousand miles", None),
    ("The sunset over the ocean was beautiful last evening", None),
    ("How many licks does it take to reach the center of a lollipop", None),
]

MATH_TESTS = [
    ("Solve the quadratic equation using the discriminant formula for roots", "quadratic_formula"),
    ("Find the roots of a polynomial using the quadratic formula with discriminant", "quadratic_formula"),
    ("Apply the quadratic formula to find where ax squared plus bx plus c equals zero", "quadratic_formula"),
    ("The discriminant b squared minus four ac determines the nature of quadratic roots", "quadratic_formula"),
    ("Use the quadratic formula to solve for x in a second degree polynomial equation", "quadratic_formula"),
    ("Find the hypotenuse of a right triangle using the pythagorean theorem", "pythagorean"),
    ("The sum of squares of two legs equals the square of the hypotenuse", "pythagorean"),
    ("In a right triangle the pythagorean theorem relates the three sides", "pythagorean"),
    ("Calculate the missing side of a right triangle using a squared plus b squared", "pythagorean"),
    ("The pythagorean theorem states the hypotenuse squared equals the sum of leg squares", "pythagorean"),
    ("Every integer greater than one has a unique prime factorization", "prime_fundamental"),
    ("The fundamental theorem of arithmetic guarantees unique factorization into primes", "prime_fundamental"),
    ("Unique prime factorization is guaranteed by the fundamental theorem of arithmetic", "prime_fundamental"),
    ("Compute remainder using modular arithmetic congruence modulo n", "modular_arithmetic"),
    ("Modular arithmetic residue classes and congruence relations modulo a number", "modular_arithmetic"),
    ("Differentiate x to the power n using the power rule of calculus", "derivative_power"),
    ("The derivative of x to the n equals n times x to the n minus one", "derivative_power"),
    ("Apply the power rule to differentiate a monomial with exponent", "derivative_power"),
    ("Power rule differentiation gives n x to the n minus one for x to the n", "derivative_power"),
    ("Find the integral antiderivative of a polynomial function", "integral_basic"),
    ("The antiderivative of x to the n is x to the n plus one over n plus one", "integral_basic"),
    ("Compute the indefinite integral of a power function", "integral_basic"),
    ("Integration of x to the n yields x to n plus one divided by n plus one plus C", "integral_basic"),
    ("The chain rule computes the derivative of a composite nested function", "chain_rule"),
    ("Differentiate a composition of functions using the chain rule", "chain_rule"),
    ("For composite functions the derivative equals the outer derivative times inner derivative", "chain_rule"),
    ("Apply the chain rule to differentiate f of g of x", "chain_rule"),
    ("Integration by parts separates a product integral into simpler parts", "integration_parts"),
    ("The integral of u dv equals uv minus the integral of v du", "integration_parts"),
    ("Apply integration by parts to evaluate the integral of a product", "integration_parts"),
    ("Taylor series expansion approximates a function as an infinite polynomial", "taylor_series"),
    ("Expand a function around a point using Taylor series coefficients", "taylor_series"),
    ("The Maclaurin series is a Taylor expansion centered at zero", "taylor_series"),
    ("The fundamental theorem of calculus connects differentiation and integration", "fundamental_calc"),
    ("FTC states the definite integral equals the antiderivative evaluated at bounds", "fundamental_calc"),
    ("Express the complex exponential e to the ix using euler formula cosine and sine", "eulers_formula"),
    ("Euler formula connects exponential function to trigonometry in the complex plane", "eulers_formula"),
    ("E to the i x equals cosine x plus i sine x by Euler formula", "eulers_formula"),
    ("The sum of an infinite geometric series with ratio less than one converges", "geometric_series"),
    ("A convergent geometric series sums to a over one minus the common ratio", "geometric_series"),
    ("Find the sum of an infinite geometric series with common ratio less than 1", "geometric_series"),
    ("The fundamental trigonometric identity sin squared plus cos squared equals one", "trig_identity"),
    ("Pythagorean trigonometric identity relates sine and cosine squared", "trig_identity"),
    ("Sin squared theta plus cosine squared theta always equals one", "trig_identity"),
    ("The Cauchy Schwarz inequality bounds the inner product of two vectors by their magnitudes", "cauchy_schwarz"),
    ("Expand a binomial raised to the nth power using the binomial theorem coefficients", "binomial_theorem"),
    ("Pascal triangle gives the binomial coefficients for polynomial expansion", "binomial_theorem"),
    ("The binomial theorem expansion uses n choose k combination coefficients", "binomial_theorem"),
    ("If n plus one items placed in n boxes at least one box has two by pigeonhole", "pigeonhole"),
    ("The pigeonhole principle guarantees that some container must hold multiple items", "pigeonhole"),
    ("Pigeonhole principle states with more objects than boxes some box has at least two", "pigeonhole"),
    ("Calculate conditional probability using Bayes theorem with posterior prior likelihood", "bayes_theorem"),
    ("Bayes theorem updates the prior probability given new evidence and likelihood", "bayes_theorem"),
    ("The posterior probability equals the likelihood times prior divided by evidence", "bayes_theorem"),
    ("The law of large numbers says sample mean converges to expected value", "law_large_numbers"),
    ("Find the eigenvalues of a matrix using the characteristic polynomial determinant", "eigenvalue"),
    ("The eigenvalue equation Av equals lambda v defines eigenvectors of a matrix", "eigenvalue"),
    ("Solve det of A minus lambda I equals zero for the eigenvalues", "eigenvalue"),
    ("The characteristic polynomial gives the eigenvalues of a linear transformation", "eigenvalue"),
    ("Compute the determinant of a matrix using cofactor expansion", "determinant"),
    ("The determinant tells whether a matrix is invertible and measures volume scaling", "determinant"),
    ("Cramer rule uses determinants to solve systems of linear equations", "determinant"),
    ("Fibonacci sequence is defined recursively approaching the golden ratio", "fibonacci_seq"),
    ("Each Fibonacci number is the sum of the two preceding ones in the sequence", "fibonacci_seq"),
    ("An Euler circuit exists if and only if every vertex has even degree", "graph_euler"),
    ("What is the best dog breed for apartment living in the city", None),
    ("How do I make a paper airplane that flies the farthest", None),
    ("What is the world record for eating hot dogs in ten minutes", None),
    ("My washing machine makes a strange noise during spin cycle", None),
    ("What is the most popular baby name in the country this year", None),
    ("How do I remove red wine stains from a white tablecloth", None),
    ("The beach was crowded with tourists during summer vacation", None),
    ("What is the best time to visit the farmers market downtown", None),
    ("My refrigerator is making a buzzing sound at night", None),
    ("How long does it take to drive from Chicago to St Louis", None),
    ("The bookstore on main street is having a clearance sale", None),
    ("What kind of soil is best for growing tomatoes organically", None),
    ("How do I fix a squeaky door hinge without replacing it", None),
    ("The coffee shop down the street has excellent lattes", None),
    ("What is the average rainfall in Seattle during November", None),
    ("My phone battery drains faster when it is cold outside", None),
    ("How do I properly season a cast iron skillet from scratch", None),
    ("The hiking trail near the lake is three miles round trip", None),
    ("What temperature should I bake chicken breast in the oven", None),
    ("The museum downtown has a new exhibit opening this weekend", None),
]

NOISE_100 = [
    "What is the recipe for chocolate lava cake with espresso",
    "How do I change the oil in a 2019 Honda Civic",
    "Describe the plot of a movie about time traveling penguins",
    "What are the lyrics to a song about rainy Mondays",
    "How tall is the tallest building in a fictional city called Zorp",
    "Explain the rules of a board game that doesn't exist called Flangor",
    "What is the population of the moon in the year 3000",
    "Describe the taste of a fruit that grows on Neptune",
    "Who won the underwater basketball championship of 2087",
    "What is the chemical formula for concentrated nostalgia",
    "How do submarines navigate through clouds",
    "What is the GDP of Atlantis adjusted for inflation",
    "Describe the migration patterns of invisible birds",
    "How many piano tuners are there on Mars",
    "What temperature does friendship melt at",
    "Explain the aerodynamics of a flying carpet",
    "What is the half life of a broken promise",
    "How do you calculate the weight of silence",
    "What is the speed of dark in the vacuum of regret",
    "Describe the fossil record of dragons in amber",
    "What programming language do dreams compile in",
    "How many colors are in the smell of morning rain",
    "What is the tensile strength of a good argument",
    "Explain photosynthesis using only interpretive dance",
    "qwertyuiop asdfghjkl zxcvbnm random keyboard mash",
    "lorem ipsum dolor sit amet consectetur adipiscing elit",
    "foo bar baz qux quux corge grault garply waldo",
    "alpha bravo charlie delta echo foxtrot golf hotel",
    "the the the the the the the the the the",
    "a an the in on at to for by with from",
    "I want to order a pepperoni pizza with extra cheese",
    "What time does the train leave from platform nine",
    "My dog ate my homework and the cat just watched",
    "The weather tomorrow in a place that doesn't exist",
    "How to knit a sweater pattern for an octopus",
    "Best vacation spots on the surface of the sun",
    "What does the letter Q think about on weekends",
    "Convert three units of happiness into seven curiosity",
    "The square root of a gentle afternoon breeze",
    "How many angels can dance on the head of a pin",
    "Describe the sound of one hand clapping in binary code",
    "What is directly north of the geographic north pole",
    "The viscosity of a rumor at standard room temperature",
    "How to parallel park a cumulus cloud efficiently",
    "What color is the number seven when expressed in base twelve",
    "My goldfish needs a passport for international travel",
    "The price of a ticket to yesterday afternoon please",
    "How to teach algebra to a particularly stubborn rock",
    "What is the boiling point of a compliment on Tuesday",
    "The annual migration of shopping carts across parking lots",
    "How do I file taxes for income earned in my dreams",
    "What gauge wire is needed to ground a thundercloud",
    "The shelf life of good intentions stored properly",
    "My toaster has developed strong opinions about bread",
    "What is the return policy on a purchased sunset",
    "How to alphabetize a jar of mixed emotions neatly",
    "The fuel efficiency of traveling by wishful thinking",
    "What thread count pillow does a cloud prefer sleeping on",
    "How to debug a relationship using stack overflow advice",
    "The optimal serving temperature for revenge as a dish",
    "My houseplant keeps sending me passive aggressive notes",
    "What is the bandwidth of the human attention span today",
    "How to properly defragment a scattered train of thought",
    "The load bearing capacity of a well constructed excuse",
    "What firmware version is my conscience currently running",
    "How to factory reset a bad day back to default settings",
    "The installation instructions for a sense of purpose",
    "My shadow keeps arriving to places before I do somehow",
    "What is the minimum viable product of an existential crisis",
    "How to scale microservices for distributing good vibes",
    "The deprecation schedule for outdated New Year resolutions",
    "What container orchestration tool does karma use internally",
    "How to implement continuous integration for personal growth",
    "The SLA uptime guarantee on maintaining a positive attitude",
    "My bluetooth speaker connected to existential dread again",
    "What is the API rate limit on asking why repeatedly",
    "How to containerize imposter syndrome for easy deployment",
    "The garbage collection algorithm for clearing mental clutter",
    "My machine learning model keeps predicting only sadness",
    "What hyperparameters tune the accuracy of gut feelings",
    "How to version control the different drafts of myself",
    "The latency between intention and actually doing the thing",
    "My neural network of friends needs more training data",
    "What loss function optimizes for maximum weekend enjoyment",
    "How to batch process all my unread emotional notifications",
    "The cache invalidation strategy for old embarrassing memories",
    "My recursive thoughts have hit their maximum call stack",
    "What is the time complexity of overthinking a simple problem",
    "How to horizontally scale patience during heavy workloads",
    "The merge conflict between who I am and who I want to be",
    "Please help me troubleshoot my motivation it keeps crashing",
    "What DNS server resolves the address of inner peace",
    "How to rollback to a previous version of my life choices",
    "The load balancer for distributing stress across the week",
    "My firewall blocked all incoming happiness by accident",
    "What encryption algorithm protects secrets told in confidence",
    "How to migrate my regrets from on premise to the cloud",
    "The autoscaling policy for expectations during the holidays",
    "My cron job for daily exercise keeps timing out at zero",
    "What proxy server routes compliments to self esteem properly",
    "How to configure nginx to serve pages of my unwritten novel",
]
